### ISSUE TITLE
test_2_dont_redirect_target_file

### ISSUE THREAD

**Issue by naumansiddiqui4** [ibnesayeed/webserver-tester#20]
Request header has head method and it expects a payload in the response. Is it the correct behavior?

Failures
ASSERTION: Payload should contain Pro Street 1966 Ford Galaxie
Original Request
HEAD /a2-test/galaxie.html HTTP/1.1
Host: cs531-msiddique
Connection: close

Original Response (Payload: 0 bytes, Connection: closed)
HTTP/1.1 200 OK
Date: Wed, 24 Oct 2018 05:58:55 GMT
Server: Assignment1/Version/0.1
Content-Length: 96
Last-Modified: Sat, 20 Oct 2018 03:44:27 GMT
Etag: "7d344af10346d1a6f168ecc66d6885af"
Content-Type: text/html
Connection: close

**Comment by ibnesayeed** [comment]
That was a typo on my side, it is fixed now. Thanks for reporting.
