### ISSUE TITLE
Path for A4 test cases

### ISSUE THREAD

**Issue by naumansiddiqui4** [ibnesayeed/webserver-tester#36]
Hello, 

On extracting the dataset a4-test.tar.gz, my directory structure is /home/mln/public_html/teaching/cs595-s12/a4-test/ from the root folder. 

I can see all the test cases testing from a4-test/ path. It makes test cases fail for my code. 

The only solution I understand for my code to run is append hard coded path in case of a4-test/ or you might have to accommodate the  new dataset file structure.

**Comment by ibnesayeed** [comment]
I think the tar file was fixed with correct paths later. Try downloading
the new version from the repository.

Best,

--
Sawood Alam
Department of Computer Science
Old Dominion University
Norfolk VA 23529

**Comment by naumansiddiqui4** [comment]
Thanks for reminding me. I can see the changes.

Thanks & Regards,
Mohammed Nauman Siddique

**Comment by ibnesayeed** [comment]
Considering this to be fixed.
