### ISSUE TITLE
cs531a5: test_10

### ISSUE THREAD

**Issue by naumansiddiqui4** [ibnesayeed/webserver-tester#42]
DELETE /a5-test/limited3/foobar.txt HTTP/1.1
User-Agent: <USERAGENT>
Authorization: Basic YmRhOmJkYQ==
Host: cs531-msiddique:80

Is, the useragent value supposed to be <USERAGENT>?

**Comment by naumansiddiqui4** [comment]
The useragent value is in angled brackets. Could you check the request once.

**Comment by ibnesayeed** [comment]
Thanks for reporting this. I forgot to supply the placeholder value in that test case. This has now been fixed and some other typos are now corrected. That said, `<USERAGENT>` is a perfectly valid UA otherwise.
