### ISSUE TITLE
cs531a5: test_put_success_auth_digest

### ISSUE THREAD

**Issue by naumansiddiqui4** [ibnesayeed/webserver-tester#43]
PUTT http://cs531-msiddique/a5-test/limited4/foo/barbar.txt HTTP/1.1
Host: cs531-msiddique:80
Authorization: Digest username="bda", realm="Colonial Place", uri="http://cs531-msiddique/a5-test/limited4/foo/barbar.txt", qop=auth, nonce="MTU0NDQ5MjQ0MC42NTEyNCA4YjYyMDQ1MjZiZmM0MzQ2MDhlMTIyY2QyNmQ5MzdhOA", nc=00000001, cnonce="014a54548c61ba03827ef6a4dc2f7b4c", response="d61beb3d1374c5f5e7fb33f8da34f99d"
Connection: close
Content-Type: text/plain

Function requested is PUTT in the request. I returned 501 response code and assertion expects 201.

**Comment by ibnesayeed** [comment]
This was a typo which has been fixed now. Thanks for reporting the issue.
