### ISSUE TITLE
cs531a5 - testsuite not available

### ISSUE THREAD

**Issue by pshankar04** [ibnesayeed/webserver-tester#46]
Hi Sawood,

I believe you have not added the a5 test suite on the repo. 

Could you please add the same, so that we can test locally.

**Thanks
Puneeth**

**Comment by ibnesayeed** [comment]
The code was here in the repo in a separate `a5` branch. I have merge the corresponding PR #41 to make those changes available in the `master` branch as well.

Note that the code structure has been changed recently, so the CLI API is now a little different. Use the following command to run all test cases of the Assignment 5 test suite:

```
$ ./main.py <hostname>:<port> cs531a5
```

And to run a specific test case (say, `test_delete_not_allowed`) in the `cs531a5` test suite use the following command:

```
$ ./main.py <hostname>:<port> cs531a5 test_delete_not_allowed
```
