### ISSUE TITLE
cs531a5: test_cgi_auth_internal_error

### ISSUE THREAD

**Issue by naumansiddiqui4** [ibnesayeed/webserver-tester#48]
```
GET http://cs531-msiddique/a5-test/500.cgi HTTP/1.1
Host: cs531-msiddique:80
Connection: close
```

If, the tester is looking for status code 500, then I do not think it can be generated by the script.

Content of Script:

```
#!/usr/bin/perl

#print "Content-type: text/plain\n\n";

$ls = `ls -alR`;

print "$ls\n";
```

**Comment by ibnesayeed** [comment]
This yields an invalid CGI output as it doesn't include any header lines (notice that the `Content-Type` header print statement is commented out). Hence, your web server should fail to interpret it and return `500` response.
