### ISSUE TITLE
Docker container not getting created

### ISSUE THREAD

**Issue by naumansiddiqui4** [ibnesayeed/webserver-tester#50]
Reusing existing image `cs531/msiddique:a5` to redeploy the service
409 Client Error: Conflict ("Conflict. The container name "/cs531-msiddique" is already in use by container "e4c9f334ff3e156522198f8d417dff19a6956d7add921093e0376886e1b6de82". You have to remove (or rename) that container to be able to reuse that name.")
Service deployment failed

**Comment by ibnesayeed** [comment]
The system had some NFS issues which are now resolved and you should now be able to deploy your service and run tests.
